In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

In [7]:
dataset = pd.read_csv(r"C:\Users\88001381\Desktop\PV_Model_Data(1).csv")

In [8]:
dataset1 = pd.read_csv(r"C:\Users\88001381\Desktop\PV_Model_Data(3).csv")

In [9]:
X_train = dataset.iloc[:, :-1]  
y_train = dataset1.iloc[:, -1]

In [10]:
rf_classifier = RandomForestClassifier(n_estimators=100, criterion = 'entropy', random_state=0, max_depth = 100)

In [13]:
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=100, random_state=0)

In [14]:
y_pred = rf_classifier.predict(X_train)

In [15]:
conf_matrix = confusion_matrix(y_train, y_pred)
print(conf_matrix)

[[122461      1]
 [     8  12550]]

In [16]:
from sklearn.metrics import precision_score, \
    recall_score, confusion_matrix, classification_report, \
    accuracy_score, f1_score

In [19]:
print('Accuracy:', accuracy_score(y_train, y_pred))
print('F1 score:', f1_score(y_train, y_pred))
print('Recall:', recall_score(y_train, y_pred))
print('Precision:', precision_score(y_train, y_pred))

Accuracy: 0.9999333432084135
F1 score: 0.9996415627862519
Recall: 0.999362955884695
Precision: 0.9999203250736993

In [22]:
import seaborn as sns

In [24]:
dataset

,Month,FIN_AMOUNT,IRR_CUSTOMER,ASSET_COST,LTV,COLLECTION_TILL_DATE,SOHP,TENURE,ODAMT,COLLECTION_MONTH,...,ASSET_CATEGORY2_B,NORM_B,CUSTOMER_SEGMENT_B,COMPANY_INDIVIDUAL_B,SOURCING_B,PDC_FLAG_B,SCHEME_FINPROD_B,TRACK_RECORD_B,REGION_NEW_B,Restructuring_Flag_B
0,202112,700000.0,9.981,932886.0,0.750360,474180.0,317226.730,36,0.0,22580.0,...,0,2,0,1,0,2,3,0,0,3
1,202203,509126.0,11.359,676423.0,0.708274,52920.0,485118.420,84,0.0,8820.0,...,0,5,6,1,0,2,3,1,0,3
2,202207,120169.0,13.968,135227.0,0.888646,14020.0,120077.180,12,0.0,1402.0,...,0,3,1,1,2,1,9,1,0,0
3,202112,1707863.0,9.889,1707863.0,1.000000,1310624.0,555053.570,23,0.0,81914.0,...,0,2,0,0,2,2,8,1,1,3
4,202202,493011.0,11.525,646244.0,0.752804,77000.0,448698.050,59,0.0,11000.0,...,0,2,0,1,1,2,3,1,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135015,202204,530038.0,11.552,686837.0,0.755773,158889.0,452584.230,83,0.0,9300.0,...,0,2,0,1,1,2,6,2,0,3
135016,202205,574497.0,10.047,688765.0,0.820309,398310.0,29217.259,60,0.0,12070.0,...,0,6,3,1,0,2,6,1,0,3
135017,202112,75991.0,13.978,113800.0,0.667759,2661.0,75947.810,12,0.0,887.0,...,0,3,5,1,2,1,9,1,2,0
135018,202111,39167.0,13.960,96329.0,0.406596,914.0,39182.130,12,0.0,457.0,...,0,3,5,1,2,1,9,1,0,0
135019,202109,500129.0,9.220,717742.0,0.689663,73108.0,453248.000,60,0.0,10444.0,...,0,2,0,1,0,2,3,1,0,3

In [25]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135020 entries, 0 to 135019
Data columns (total 69 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Month                 135020 non-null  int64
 1   FIN_AMOUNT            135020 non-null  float64
 2   IRR_CUSTOMER          135020 non-null  float64
 3   ASSET_COST            135020 non-null  float64
 4   LTV                   135020 non-null  float64
 5   COLLECTION_TILL_DATE  135020 non-null  float64
 6   SOHP                  135020 non-null  float64
 7   TENURE                135020 non-null  int64
 8   ODAMT                 135020 non-null  float64
 9   COLLECTION_MONTH      135020 non-null  float64
 10  FIRST_EMI             135020 non-null  int64
 11  EMI                   135020 non-null  float64
 12  ODBKT                 135020 non-null  int64
 13  INCEPTION_MONTH       135020 non-null  int64
 14  MOB                   135020 non-null  int64
 15  SOHPOD                135020 non-null  float64
 16  SOHPOD_PREASSIGN      135020 non-null  float64
 17  PAID_PER              135020 non-null  float64
 18  TENURE_LEFT           135020 non-null  int64
 19  max_odbkt             135020 non-null  int64
 20  Ever_30               135020 non-null  int64
 21  Ever_60               135020 non-null  int64
 22  Ever_90               135020 non-null  int64
 23  max_dpd               135020 non-null  int64
 24  EverInBkt_1_3M        135020 non-null  int64
 25  EverInBkt_2_3M        135020 non-null  int64
 26  EverInBkt_3_3M        135020 non-null  int64
 27  EverInBkt_4Plus_3M    135020 non-null  int64
 28  EverInBkt_1_6M        135020 non-null  int64
 29  EverInBkt_2_6M        135020 non-null  int64
 30  EverInBkt_3_6M        135020 non-null  int64
 31  EverInBkt_4Plus_6M    135020 non-null  int64
 32  EverInBkt_1_9M        135020 non-null  int64
 33  EverInBkt_2_9M        135020 non-null  int64
 34  EverInBkt_3_9M        135020 non-null  int64
 35  EverInBkt_4Plus_9M    135020 non-null  int64
 36  EverInBkt_1_12M       135020 non-null  int64
 37  EverInBkt_2_12M       135020 non-null  int64
 38  EverInBkt_3_12M       135020 non-null  int64
 39  EverInBkt_4Plus_12M   135020 non-null  int64
 40  MaxBkt_24M            135020 non-null  int64
 41  MinBkt_24M            135020 non-null  int64
 42  Mode_Bkt_24M          135020 non-null  int64
 43  SDBkt_24M             135020 non-null  float64
 44  Tot_X_6M              135020 non-null  int64
 45  Tot_X_3M              135020 non-null  int64
 46  Bounce_1M             135020 non-null  int64
 47  Last_2M_Cons_Del      135020 non-null  int64
 48  Last_3M_Cons_Del      135020 non-null  int64
 49  Last_6M_Cons_Del      135020 non-null  int64
 50  Del_in_Last_12M       135020 non-null  int64
 51  ASSET_LTV             135020 non-null  float64
 52  ME1                   135020 non-null  float64
 53  CE1                   135020 non-null  float64
 54  PRODUCT_B             135020 non-null  int64
 55  STATE_B               135020 non-null  int64
 56  IRR_CUSTOMER_D        135020 non-null  int64
 57  APPLICATION_USAGE_B   135020 non-null  int64
 58  BRANCH_NEW_B          135020 non-null  int64
 59  ASSET_CATEGORY2_B     135020 non-null  int64
 60  NORM_B                135020 non-null  int64
 61  CUSTOMER_SEGMENT_B    135020 non-null  int64
 62  COMPANY_INDIVIDUAL_B  135020 non-null  int64
 63  SOURCING_B            135020 non-null  int64
 64  PDC_FLAG_B            135020 non-null  int64
 65  SCHEME_FINPROD_B      135020 non-null  int64
 66  TRACK_RECORD_B        135020 non-null  int64
 67  REGION_NEW_B          135020 non-null  int64
 68  Restructuring_Flag_B  135020 non-null  int64
dtypes: float64(16), int64(53)
memory usage: 71.1 MB

In [26]:
dataset.Column

AttributeError: 'DataFrame' object has no attribute 'Column'

In [27]:
print(dataset)

         Month  FIN_AMOUNT  IRR_CUSTOMER  ASSET_COST       LTV  \
0       202112    700000.0         9.981    932886.0  0.750360
1       202203    509126.0        11.359    676423.0  0.708274
2       202207    120169.0        13.968    135227.0  0.888646
3       202112   1707863.0         9.889   1707863.0  1.000000
4       202202    493011.0        11.525    646244.0  0.752804
...        ...         ...           ...         ...       ...
135015  202204    530038.0        11.552    686837.0  0.755773
135016  202205    574497.0        10.047    688765.0  0.820309
135017  202112     75991.0        13.978    113800.0  0.667759
135018  202111     39167.0        13.960     96329.0  0.406596
135019  202109    500129.0         9.220    717742.0  0.689663

        COLLECTION_TILL_DATE        SOHP  TENURE  ODAMT  COLLECTION_MONTH  \
0                   474180.0  317226.730      36    0.0           22580.0
1                    52920.0  485118.420      84    0.0            8820.0
2                    14020.0  120077.180      12    0.0            1402.0
3                  1310624.0  555053.570      23    0.0           81914.0
4                    77000.0  448698.050      59    0.0           11000.0
...                      ...         ...     ...    ...               ...
135015              158889.0  452584.230      83    0.0            9300.0
135016              398310.0   29217.259      60    0.0           12070.0
135017                2661.0   75947.810      12    0.0             887.0
135018                 914.0   39182.130      12    0.0             457.0
135019               73108.0  453248.000      60    0.0           10444.0

        ...  ASSET_CATEGORY2_B  NORM_B  CUSTOMER_SEGMENT_B  \
0       ...                  0       2                   0
1       ...                  0       5                   6
2       ...                  0       3                   1
3       ...                  0       2                   0
4       ...                  0       2                   0
...     ...                ...     ...                 ...
135015  ...                  0       2                   0
135016  ...                  0       6                   3
135017  ...                  0       3                   5
135018  ...                  0       3                   5
135019  ...                  0       2                   0

        COMPANY_INDIVIDUAL_B  SOURCING_B  PDC_FLAG_B  SCHEME_FINPROD_B  \
0                          1           0           2                 3
1                          1           0           2                 3
2                          1           2           1                 9
3                          0           2           2                 8
4                          1           1           2                 3
...                      ...         ...         ...               ...
135015                     1           1           2                 6
135016                     1           0           2                 6
135017                     1           2           1                 9
135018                     1           2           1                 9
135019                     1           0           2                 3

        TRACK_RECORD_B  REGION_NEW_B  Restructuring_Flag_B
0                    0             0                     3
1                    1             0                     3
2                    1             0                     0
3                    1             1                     3
4                    1             1                     3
...                ...           ...                   ...
135015               2             0                     3
135016               1             0                     3
135017               1             2                     0
135018               1             0                     0
135019               1             0                     3

[135020 rows x 69 columns]

In [28]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(dataset.isnull().sum())

Month                   0
FIN_AMOUNT              0
IRR_CUSTOMER            0
ASSET_COST              0
LTV                     0
COLLECTION_TILL_DATE    0
SOHP                    0
TENURE                  0
ODAMT                   0
COLLECTION_MONTH        0
FIRST_EMI               0
EMI                     0
ODBKT                   0
INCEPTION_MONTH         0
MOB                     0
SOHPOD                  0
SOHPOD_PREASSIGN        0
PAID_PER                0
TENURE_LEFT             0
max_odbkt               0
Ever_30                 0
Ever_60                 0
Ever_90                 0
max_dpd                 0
EverInBkt_1_3M          0
EverInBkt_2_3M          0
EverInBkt_3_3M          0
EverInBkt_4Plus_3M      0
EverInBkt_1_6M          0
EverInBkt_2_6M          0
EverInBkt_3_6M          0
EverInBkt_4Plus_6M      0
EverInBkt_1_9M          0
EverInBkt_2_9M          0
EverInBkt_3_9M          0
EverInBkt_4Plus_9M      0
EverInBkt_1_12M         0
EverInBkt_2_12M         0
EverInBkt_3_12M         0
EverInBkt_4Plus_12M     0
MaxBkt_24M              0
MinBkt_24M              0
Mode_Bkt_24M            0
SDBkt_24M               0
Tot_X_6M                0
Tot_X_3M                0
Bounce_1M               0
Last_2M_Cons_Del        0
Last_3M_Cons_Del        0
Last_6M_Cons_Del        0
Del_in_Last_12M         0
ASSET_LTV               0
ME1                     0
CE1                     0
PRODUCT_B               0
STATE_B                 0
IRR_CUSTOMER_D          0
APPLICATION_USAGE_B     0
BRANCH_NEW_B            0
ASSET_CATEGORY2_B       0
NORM_B                  0
CUSTOMER_SEGMENT_B      0
COMPANY_INDIVIDUAL_B    0
SOURCING_B              0
PDC_FLAG_B              0
SCHEME_FINPROD_B        0
TRACK_RECORD_B          0
REGION_NEW_B            0
Restructuring_Flag_B    0
dtype: int64