In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv(r"C:\Users\88001381\OneDrive - Tata Motors Finance\Desktop\PV_Model_Data_Orignal.csv")

In [3]:
print(dataset)

         Month  FIN_AMOUNT  IRR_CUSTOMER  ASSET_COST       LTV  \
0       202112    700000.0         9.981    932886.0  0.750360
1       202203    509126.0        11.359    676423.0  0.708274
2       202207    120169.0        13.968    135227.0  0.888646
3       202112   1707863.0         9.889   1707863.0  1.000000
4       202202    493011.0        11.525    646244.0  0.752804
...        ...         ...           ...         ...       ...
135015  202204    530038.0        11.552    686837.0  0.755773
135016  202205    574497.0        10.047    688765.0  0.820309
135017  202112     75991.0        13.978    113800.0  0.667759
135018  202111     39167.0        13.960     96329.0  0.406596
135019  202109    500129.0         9.220    717742.0  0.689663

        COLLECTION_TILL_DATE        SOHP  TENURE  ODAMT  COLLECTION_MONTH  \
0                   474180.0  317226.730      36    0.0           22580.0
1                    52920.0  485118.420      84    0.0            8820.0
2                    14020.0  120077.180      12    0.0            1402.0
3                  1310624.0  555053.570      23    0.0           81914.0
4                    77000.0  448698.050      59    0.0           11000.0
...                      ...         ...     ...    ...               ...
135015              158889.0  452584.230      83    0.0            9300.0
135016              398310.0   29217.259      60    0.0           12070.0
135017                2661.0   75947.810      12    0.0             887.0
135018                 914.0   39182.130      12    0.0             457.0
135019               73108.0  453248.000      60    0.0           10444.0

        ...  ASSET_CATEGORY2_B  NORM_B  CUSTOMER_SEGMENT_B  \
0       ...                  0       2                   0
1       ...                  0       5                   6
2       ...                  0       3                   1
3       ...                  0       2                   0
4       ...                  0       2                   0
...     ...                ...     ...                 ...
135015  ...                  0       2                   0
135016  ...                  0       6                   3
135017  ...                  0       3                   5
135018  ...                  0       3                   5
135019  ...                  0       2                   0

        COMPANY_INDIVIDUAL_B  SOURCING_B  PDC_FLAG_B  SCHEME_FINPROD_B  \
0                          1           0           2                 3
1                          1           0           2                 3
2                          1           2           1                 9
3                          0           2           2                 8
4                          1           1           2                 3
...                      ...         ...         ...               ...
135015                     1           1           2                 6
135016                     1           0           2                 6
135017                     1           2           1                 9
135018                     1           2           1                 9
135019                     1           0           2                 3

        TRACK_RECORD_B  REGION_NEW_B  Restructuring_Flag_B
0                    0             0                     3
1                    1             0                     3
2                    1             0                     0
3                    1             1                     3
4                    1             1                     3
...                ...           ...                   ...
135015               2             0                     3
135016               1             0                     3
135017               1             2                     0
135018               1             0                     0
135019               1             0                     3

[135020 rows x 70 columns]

In [5]:
print(dataset.isnull().sum)

<bound method NDFrame._add_numeric_operations.<locals>.sum of         Month  FIN_AMOUNT  IRR_CUSTOMER  ASSET_COST    LTV  \
0       False       False         False       False  False
1       False       False         False       False  False
2       False       False         False       False  False
3       False       False         False       False  False
4       False       False         False       False  False
...       ...         ...           ...         ...    ...
135015  False       False         False       False  False
135016  False       False         False       False  False
135017  False       False         False       False  False
135018  False       False         False       False  False
135019  False       False         False       False  False

        COLLECTION_TILL_DATE   SOHP  TENURE  ODAMT  COLLECTION_MONTH  ...  \
0                      False  False   False  False             False  ...
1                      False  False   False  False             False  ...
2                      False  False   False  False             False  ...
3                      False  False   False  False             False  ...
4                      False  False   False  False             False  ...
...                      ...    ...     ...    ...               ...  ...
135015                 False  False   False  False             False  ...
135016                 False  False   False  False             False  ...
135017                 False  False   False  False             False  ...
135018                 False  False   False  False             False  ...
135019                 False  False   False  False             False  ...

        ASSET_CATEGORY2_B  NORM_B  CUSTOMER_SEGMENT_B  COMPANY_INDIVIDUAL_B  \
0                   False   False               False                 False
1                   False   False               False                 False
2                   False   False               False                 False
3                   False   False               False                 False
4                   False   False               False                 False
...                   ...     ...                 ...                   ...
135015              False   False               False                 False
135016              False   False               False                 False
135017              False   False               False                 False
135018              False   False               False                 False
135019              False   False               False                 False

        SOURCING_B  PDC_FLAG_B  SCHEME_FINPROD_B  TRACK_RECORD_B  \
0            False       False             False           False
1            False       False             False           False
2            False       False             False           False
3            False       False             False           False
4            False       False             False           False
...            ...         ...               ...             ...
135015       False       False             False           False
135016       False       False             False           False
135017       False       False             False           False
135018       False       False             False           False
135019       False       False             False           False

        REGION_NEW_B  Restructuring_Flag_B
0              False                 False
1              False                 False
2              False                 False
3              False                 False
4              False                 False
...              ...                   ...
135015         False                 False
135016         False                 False
135017         False                 False
135018         False                 False
135019         False                 False

[135020 rows x 70 columns]>

In [6]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(dataset.isnull().sum())

Month                   0
FIN_AMOUNT              0
IRR_CUSTOMER            0
ASSET_COST              0
LTV                     0
COLLECTION_TILL_DATE    0
SOHP                    0
TENURE                  0
ODAMT                   0
COLLECTION_MONTH        0
FIRST_EMI               0
EMI                     0
ODBKT                   0
INCEPTION_MONTH         0
MOB                     0
SOHPOD                  0
SOHPOD_PREASSIGN        0
PAID_PER                0
TENURE_LEFT             0
max_odbkt               0
Ever_30                 0
Ever_60                 0
Ever_90                 0
max_dpd                 0
target_variable         0
EverInBkt_1_3M          0
EverInBkt_2_3M          0
EverInBkt_3_3M          0
EverInBkt_4Plus_3M      0
EverInBkt_1_6M          0
EverInBkt_2_6M          0
EverInBkt_3_6M          0
EverInBkt_4Plus_6M      0
EverInBkt_1_9M          0
EverInBkt_2_9M          0
EverInBkt_3_9M          0
EverInBkt_4Plus_9M      0
EverInBkt_1_12M         0
EverInBkt_2_12M         0
EverInBkt_3_12M         0
EverInBkt_4Plus_12M     0
MaxBkt_24M              0
MinBkt_24M              0
Mode_Bkt_24M            0
SDBkt_24M               0
Tot_X_6M                0
Tot_X_3M                0
Bounce_1M               0
Last_2M_Cons_Del        0
Last_3M_Cons_Del        0
Last_6M_Cons_Del        0
Del_in_Last_12M         0
ASSET_LTV               0
ME1                     0
CE1                     0
PRODUCT_B               0
STATE_B                 0
IRR_CUSTOMER_D          0
APPLICATION_USAGE_B     0
BRANCH_NEW_B            0
ASSET_CATEGORY2_B       0
NORM_B                  0
CUSTOMER_SEGMENT_B      0
COMPANY_INDIVIDUAL_B    0
SOURCING_B              0
PDC_FLAG_B              0
SCHEME_FINPROD_B        0
TRACK_RECORD_B          0
REGION_NEW_B            0
Restructuring_Flag_B    0
dtype: int64

In [7]:
dataset1 = pd.read_csv(r"C:\Users\88001381\Desktop\test_with_binning(1).csv")

In [8]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(dataset1.isnull().sum())

Month                   0
FIN_AMOUNT              0
IRR_CUSTOMER            0
ASSET_COST              0
LTV                     0
COLLECTION_TILL_DATE    0
SOHP                    0
TENURE                  0
ODAMT                   0
COLLECTION_MONTH        0
FIRST_EMI               0
EMI                     0
ODBKT                   0
INCEPTION_MONTH         0
MOB                     0
SOHPOD                  0
SOHPOD_PREASSIGN        0
PAID_PER                0
TENURE_LEFT             0
max_odbkt               0
Ever_30                 0
Ever_60                 0
Ever_90                 0
max_dpd                 0
EverInBkt_1_3M          0
EverInBkt_2_3M          0
EverInBkt_3_3M          0
EverInBkt_4Plus_3M      0
EverInBkt_1_6M          0
EverInBkt_2_6M          0
EverInBkt_3_6M          0
EverInBkt_4Plus_6M      0
EverInBkt_1_9M          0
EverInBkt_2_9M          0
EverInBkt_3_9M          0
EverInBkt_4Plus_9M      0
EverInBkt_1_12M         0
EverInBkt_2_12M         0
EverInBkt_3_12M         0
EverInBkt_4Plus_12M     0
MaxBkt_24M              0
MinBkt_24M              0
Mode_Bkt_24M            0
SDBkt_24M               0
Tot_X_6M                0
Tot_X_3M                0
Bounce_1M               0
Last_2M_Cons_Del        0
Last_3M_Cons_Del        0
Last_6M_Cons_Del        0
Del_in_Last_12M         0
ASSET_LTV               0
ME1                     0
CE1                     0
PRODUCT_B               0
NORM_B                  0
APPLICATION_USAGE_B     0
ASSET_CATEGORY2_B       0
STATE_B                 0
REGION_NEW_B            0
IRR_CUSTOMER_B          0
CUSTOMER_SEGMENT_B      0
COMPANY_INDIVIDUAL_B    0
SOURCING_B              0
PDC_FLAG_B              0
SCHEME_FINPROD_B        0
TRACK_RECORD_B          0
Restructuring_Flag_B    0
BRANCH_NEW_B            0
dtype: int64

In [9]:
print(dataset1)

        Month  FIN_AMOUNT  IRR_CUSTOMER  ASSET_COST       LTV  \
0      202206    386000.0         8.767    482920.0  0.799304
1      202203    539797.0         9.829    635635.0  0.841678
2      202208    673997.0         9.626    809480.0  0.825221
3      202203    450000.0         9.809    619006.0  0.726972
4      202204    332464.0        10.054    403489.0  0.817866
...       ...         ...           ...         ...       ...
57854  202202     88140.0        13.995    132268.0  0.666374
57855  202109    230376.0        14.000    230376.0  1.000000
57856  202110     92152.0        13.997     92152.0  1.000000
57857  202111    656495.0        10.476    856953.0  0.766081
57858  202110    403322.0         9.739    434358.0  0.920899

       COLLECTION_TILL_DATE         SOHP  TENURE  ODAMT  COLLECTION_MONTH  \
0                  430272.0   46599.3100      60    0.0            7968.0
1                  445341.0   21957.4130      60    0.0           11419.0
2                  605225.0   26803.6176      60    0.0           14075.0
3                  381343.0  171444.7500      58    0.0            9775.0
4                  320454.0   89819.5100      54    0.0            8433.0
...                     ...          ...     ...    ...               ...
57854                5140.0   88171.6400      12    0.0            1028.0
57855                   0.0  230375.9900      12    0.0               0.0
57856                1075.0   92172.6200      12    0.0            1075.0
57857              126900.0  578332.8100      60    0.0           14100.0
57858              298550.0  207671.0300      69    0.0            8530.0

       ...  REGION_NEW_B  IRR_CUSTOMER_B  CUSTOMER_SEGMENT_B  \
0      ...             1               0                   0
1      ...             0             578                   4
2      ...             0             396                   5
3      ...             1             558                   0
4      ...             0             799                   5
...    ...           ...             ...                 ...
57854  ...             1            3246                   0
57855  ...             2            3251                   2
57856  ...             2            3248                   2
57857  ...             1            1156                   0
57858  ...             0             488                   4

       COMPANY_INDIVIDUAL_B  SOURCING_B  PDC_FLAG_B  SCHEME_FINPROD_B  \
0                         1           0           1                 5
1                         1           0           1                 8
2                         1           0           1                 5
3                         1           0           1                 5
4                         1           0           1                 1
...                     ...         ...         ...               ...
57854                     1           2           2                 7
57855                     1           2           2                 7
57856                     1           2           2                 7
57857                     1           0           1                 5
57858                     1           0           1                 5

       TRACK_RECORD_B  Restructuring_Flag_B  BRANCH_NEW_B
0                   1                     3             7
1                   1                     3             4
2                   1                     3             1
3                   1                     3             4
4                   1                     3             2
...               ...                   ...           ...
57854               1                     0            11
57855               1                     0            11
57856               1                     0             9
57857               1                     3             2
57858               3                     3             4

[57859 rows x 69 columns]

In [167]:
dataset2 = pd.read_excel(r"C:\Users\88001381\Desktop\test_imp_variables2.xlsx")

In [168]:
dataset2

,NORM_B,APPLICATION_USAGE_B,ASSET_CATEGORY2_B,REGION_NEW_B,IRR_CUSTOMER_B,CUSTOMER_SEGMENT_B,COMPANY_INDIVIDUAL_B,SOURCING_B,SCHEME_FINPROD_B,TRACK_RECORD_B,...,MinBkt_24M,Mode_Bkt_24M,SDBkt_24M,Tot_X_6M,Tot_X_3M,Bounce_1M,Del_in_Last_12M,ASSET_LTV,ME1,CE1
0,2,2,0,1,0,0,1,0,5,1,...,0,0,0.000000,0,0,0,0,0.799304,1.0,1.0
1,1,2,0,0,578,4,1,0,8,1,...,0,0,0.000000,0,0,0,0,0.841678,1.0,1.0
2,5,2,0,0,396,5,1,0,5,1,...,0,0,0.000000,0,0,0,0,0.825221,1.0,1.0
3,2,2,0,1,558,0,1,0,5,1,...,0,0,0.000000,0,0,0,0,0.726972,1.0,1.0
4,5,2,0,0,799,5,1,0,1,1,...,0,0,0.000000,0,0,0,0,0.817866,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57854,2,2,0,1,3246,0,1,2,7,1,...,0,0,0.000000,0,0,0,0,0.666374,1.0,1.0
57855,1,2,0,2,3251,2,1,2,7,1,...,0,0,0.000000,0,0,0,0,1.000000,1.0,1.0
57856,2,2,0,2,3248,2,1,2,7,1,...,0,0,0.000000,0,0,0,0,1.000000,1.0,1.0
57857,2,2,0,1,1156,0,1,0,5,1,...,0,0,0.000000,1,0,0,0,0.766081,1.0,1.0
57858,1,2,0,0,488,4,1,0,5,3,...,0,2,1.310216,2,2,1,3,0.920899,1.0,1.0

In [169]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

In [170]:
dataset3 = pd.read_excel(r"C:\Users\88001381\Desktop\test_t.xlsx")

In [171]:
X_test = dataset2.iloc[:, :-1]  
y_test = dataset3.iloc[:, -1]

In [262]:
rf_classifier = RandomForestClassifier(n_estimators=5, criterion = 'entropy', random_state=50, max_depth = 22)

In [263]:
rf_classifier.fit(X_test, y_test)

RandomForestClassifier(criterion='entropy', max_depth=22, n_estimators=5,
                       random_state=50)

In [264]:
y_pred = rf_classifier.predict(X_test)

In [265]:
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

[[52274   196]
 [  874  4515]]

In [266]:
from sklearn.metrics import precision_score, \
    recall_score, confusion_matrix, classification_report, \
    accuracy_score, f1_score

In [267]:
print('Accuracy:', accuracy_score(y_test, y_pred))
print('F1 score:', f1_score(y_test, y_pred))
print('Recall:', recall_score(y_test, y_pred))
print('Precision:', precision_score(y_test, y_pred))

Accuracy: 0.981506766449472
F1 score: 0.894059405940594
Recall: 0.8378177769530525
Precision: 0.9583952451708767

In [25]:
import numpy as np

In [30]:
np.corrcoef(dataset3,dataset4)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 57859

In [27]:
dataset3

       target_variable
0                    0
1                    0
2                    0
3                    0
4                    0
...                ...
57854                0
57855                0
57856                0
57857                0
57858                1

[57859 rows x 1 columns]

In [29]:
dataset4 = dataset2['COMPANY_INDIVIDUAL_B']

In [31]:
dataset4

0        1
1        1
2        1
3        1
4        1
        ..
57854    1
57855    1
57856    1
57857    1
57858    1
Name: COMPANY_INDIVIDUAL_B, Length: 57859, dtype: int64

In [32]:
import pandas as pd
from scipy.stats import pearsonr

In [33]:
corr, _ = pearsonr(dataset3, dataset4)

ValueError: shapes (57859,1) and (57859,) not aligned: 1 (dim 1) != 57859 (dim 0)

In [34]:
dataset4 = pd.read_excel(r"C:\Users\88001381\Desktop\Book1.xlsx")

In [35]:
corr, _ = pearsonr(dataset3, dataset4)

ValueError: shapes (57859,1) and (57859,1) not aligned: 1 (dim 1) != 57859 (dim 0)

In [36]:
np.corrcoef(dataset3,dataset4)

C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\function_base.py:2683: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)

MemoryError: Unable to allocate 99.8 GiB for an array with shape (115718, 115718) and data type float64

In [166]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(dataset.isnull().sum())

Month                   0
FIN_AMOUNT              0
IRR_CUSTOMER            0
ASSET_COST              0
LTV                     0
COLLECTION_TILL_DATE    0
SOHP                    0
TENURE                  0
ODAMT                   0
COLLECTION_MONTH        0
FIRST_EMI               0
EMI                     0
ODBKT                   0
INCEPTION_MONTH         0
MOB                     0
SOHPOD                  0
SOHPOD_PREASSIGN        0
PAID_PER                0
TENURE_LEFT             0
max_odbkt               0
Ever_30                 0
Ever_60                 0
Ever_90                 0
max_dpd                 0
target_variable         0
EverInBkt_1_3M          0
EverInBkt_2_3M          0
EverInBkt_3_3M          0
EverInBkt_4Plus_3M      0
EverInBkt_1_6M          0
EverInBkt_2_6M          0
EverInBkt_3_6M          0
EverInBkt_4Plus_6M      0
EverInBkt_1_9M          0
EverInBkt_2_9M          0
EverInBkt_3_9M          0
EverInBkt_4Plus_9M      0
EverInBkt_1_12M         0
EverInBkt_2_12M         0
EverInBkt_3_12M         0
EverInBkt_4Plus_12M     0
MaxBkt_24M              0
MinBkt_24M              0
Mode_Bkt_24M            0
SDBkt_24M               0
Tot_X_6M                0
Tot_X_3M                0
Bounce_1M               0
Last_2M_Cons_Del        0
Last_3M_Cons_Del        0
Last_6M_Cons_Del        0
Del_in_Last_12M         0
ASSET_LTV               0
ME1                     0
CE1                     0
PRODUCT_B               0
STATE_B                 0
IRR_CUSTOMER_D          0
APPLICATION_USAGE_B     0
BRANCH_NEW_B            0
ASSET_CATEGORY2_B       0
NORM_B                  0
CUSTOMER_SEGMENT_B      0
COMPANY_INDIVIDUAL_B    0
SOURCING_B              0
PDC_FLAG_B              0
SCHEME_FINPROD_B        0
TRACK_RECORD_B          0
REGION_NEW_B            0
Restructuring_Flag_B    0
dtype: int64

In [268]:
from sklearn.metrics import classification_report

In [269]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99     52470
           1       0.96      0.84      0.89      5389

    accuracy                           0.98     57859
   macro avg       0.97      0.92      0.94     57859
weighted avg       0.98      0.98      0.98     57859